---
After: 'toolbar/*'
---
SSViewer:
  theme: addons
GlobalNav:
  hostname: 'http://ssorg.dev/'
  css_path: '/themes/ssv3/css/toolbar.css'
  use_localhost: false
GlobalNavTemplateProvider:
  connection_timeout: 1000
  transfer_timeout: 2000