---
After: framework
---
SilverStripe\Control\Director:
  rules:
    "": SilverStripe\Addons\Controllers\HomeController
    "add-ons": SilverStripe\Addons\Controllers\AddonsController
    "vendors": SilverStripe\Addons\Controllers\VendorsController
    "authors": SilverStripe\Addons\Controllers\AuthorsController
    "tags": SilverStripe\Addons\Controllers\TagsController
    "submit": SilverStripe\Addons\Controllers\SubmitAddonController
