---
After: framework
---
Director:
  rules:
    "": HomeController
    "add-ons": AddonsController
    "vendors": VendorsController
    "authors": AuthorsController
    "tags": TagsController
    "submit": SubmitAddonController
    "addonSort": AjaxController
